import re
from datetime import datetime, timedelta, timezone

from .config import CACHE_TTL_SECONDS
from .intelligence import METHODOLOGY_VERSION

DOMAIN_RE = re.compile(r"^(?=.{1,253}$)(?!-)(?:[a-z0-9-]{1,63}\.)+[a-z]{2,63}$", re.I)


def normalize_domain(value: str) -> str:
    if not isinstance(value, str):
        raise ValueError("domain deve essere una stringa")
    domain = value.strip().rstrip(".").lower()
    if "://" in domain or "/" in domain or "@" in domain:
        raise ValueError("inserisci soltanto un nome di dominio")
    try:
        domain = domain.encode("idna").decode("ascii")
    except UnicodeError as exc:
        raise ValueError("dominio non valido") from exc
    if not DOMAIN_RE.fullmatch(domain):
        raise ValueError("dominio non valido")
    return domain


def build_report(domain: str, evidence: dict, now=None) -> dict:
    now = now or datetime.now(timezone.utc)
    # The collector owns the single passive-only scoring methodology, so the
    # published report cannot silently mix active and passive signals.
    trust = evidence.get("trust") if isinstance(evidence, dict) else None
    if isinstance(trust, dict) and isinstance(trust.get("score"), (int, float)):
        levels = {"high": "alto", "medium": "medio", "low": "basso"}
        result = {
            "trust_score": int(trust["score"]),
            "rating": levels.get(trust.get("level"), "sconosciuto"),
            "checks": [{"id": item.get("id"), "label": item.get("id", "segnale").replace("_", " "),
                        "weight": item.get("weight", 0), "points": item.get("weight", 0),
                        "status": "info", "detail": item.get("rationale", "")}
                       for item in trust.get("indicators", []) if isinstance(item, dict)],
            "disclaimer": trust.get("disclaimer", "Indicatore tecnico basato su fonti pubbliche."),
            "methodology_version": trust.get("methodology_version"),
        }
    else:
        raise ValueError("collector did not return a valid trust methodology")
    return {"domain": domain, "checked_at": now.isoformat(),
            "expires_at": (now + timedelta(seconds=CACHE_TTL_SECONDS)).isoformat(),
            "sources": evidence.get("sources", []), "evidence": evidence,
            **result}


class DomainChecker:
    def __init__(self, store, collector):
        self.store, self.collector = store, collector

    def check(self, requested_domain: str, refresh=False) -> tuple[dict, bool]:
        domain = normalize_domain(requested_domain)
        cached = None if refresh else self.store.get_fresh(domain, datetime.now(timezone.utc).isoformat())
        # Scores generated by an older methodology are deliberately not reused:
        # security-rule changes must take effect before the normal cache TTL.
        if cached and cached.get("methodology_version") == METHODOLOGY_VERSION:
            self.store.record_query(domain, True, cached["trust_score"])
            return cached, True
        evidence = self.collector(domain)
        report = build_report(domain, evidence)
        self.store.save_report(report)
        self.store.record_query(domain, False, report["trust_score"])
        return report, False
